# Site settings
title: Documentation for Click2Park
email: support@netfm.org
description: > # this means to ignore newlines until "baseurl:"
  Click2park documention is provided for both the Desktop 
  and the Mobile interfaces, with separate Desktop User Guides for all user types.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.click2park.co.uk/" # the base hostname & protocol for your site
twitter_username: click2park
github_username:  dave@netfm.org

# Build settings
markdown: kramdown
